#server:
#  port: 3034


#feign指定ip调用feign服务提供方===开始
#下面这个feign是直接调用的方式，也就是不把feign提供者和消费者注册到注册中心，直接指定ip调用，这样是没有Road Balance的（不需要如下Eureka的配置）
#feign:
#  server:
#    url: http://localhost:3033/
#feign指定ip调用feign服务提供方===结束



#Eureka注册中心配置
#spring:
#  application:
#    name: feign-client-consumer

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
